language: node_js
node_js:
  - '14'
dist: trusty
cache: npm
services:
  - mongodb
  - redis-server
env:
  - JWT_KEY=testKey
script:
  - cd ./server
  - npm install
  - nohup npm run start &
  - sleep 3
  - npm test
