version: '3'
services:
  api:
    build: ./server
    ports:
      - '8080:8080'
    depends_on:
      - db
    container_name: bjj-api
  client:
    build: ./client
    ports:
      - '3000:3000'
    container_name: bjj-client
  db:
    image: mongo
    ports:
      - '27017:27017'
    container_name: bjj-db
