language: node_js
node_js:
  - '14'
dist: trusty
services:
  - mongodb
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - nohup npm run start &
  - sleep 3
  - npm run test
